### ISSUE TITLE
User Story – Secure authenticating

### ISSUE THREAD

**Issue by MFaarkrog** [AppBones/auth-service#9]
## User Story
*As a Consumer,*
I would like to have a secure means of authenticating my End Users with my app from an untrusted context (such as a mobile app),
**so that** I can maintain the security of my app's data on the service.

----------
|| **Acceptance test** |
|---|---|
| **Prerequisites**   | a |
| **Expected Input**  | b |
| **Expected Output** | c |
----------

### Subtasks
-

**Comment by warreq** [comment]
commit 62f1cce4d57f7d9e018f7d0b2b1a280fcea38ae1 addresses this
